### ISSUE TITLE
The test suite exits half-way though when it calls Test.Spec.Runner.run

### ISSUE THREAD

**Issue by Dretch** [owickstrom/purescript-spec-reporter-xunit#3]
The offending code is here: https://github.com/owickstrom/purescript-spec-reporter-xunit/blob/master/test/Test/Spec/Reporter/XunitSpec.purs#L38

`Test.Spec.Runner.run` runs a test spec, and then exits the process, so the test suite never completes!

**Comment by owickstrom** [comment]
Oh, that's not very good. I think it's https://github.com/owickstrom/purescript-spec/blob/master/src/Test/Spec/Runner.purs#L166 that exits when run in NodeJS. The `Config` of the runner shoulds probably include a boolean field, whether to exit on success or not.
